version: "3.9"
services:
#docker run -it --publish 7000:4000 --detach terianscada
  app:
    image: teriandev/terianscada:latest
    restart: always
    ports:
      - 7000:4000
    volumes: #Solo requerido para desarrollo Local
      - .:/app

  postgres:
    image: postgres:14.3-alpine
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=terian-scada
      - DATABASE_URL=postgresql://root:root@postgres:5432/terian-scada
    volumes:
      - postgresql-volume:/var/lib/postgresql/data    
    depends_on:
      - app

volumes: 
  postgresql-volume:
    external: false
  